//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcevedoBcoProv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Empleado
    {
        internal int id;

        [Display(Name="#")]
        public int Id { get; set; }

        [Display(Name = "Codigo")]
        public string Codigo { get; set; }
        [Display(Name = "Apellido")]
        [Required(ErrorMessage = "El Apellido es obligatorio.")]
        public string Apellido { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El Nombre es obligatorio.")]
        public string Nombre { get; set; }
        [Display(Name = "Fecha de Nacimiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString ="{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }

        [Display(Name = "Tipo Documento")]
        public int IdTipoDto { get; set; }
       

        [Display(Name = "Nro Doc")]
        [Required(ErrorMessage = "El número de documento es obligatorio.")]
       
        public int NumDocumento { get; set; }
    
        public virtual TiposDocumento TiposDocumento { get; set; }


        [Display(Name = "Edad")]
        public int Edad
        {
            get
            {
                if (FechaNacimiento.HasValue)
                {
                    DateTime hoy = DateTime.Today;
                    int edad = hoy.Year - FechaNacimiento.Value.Year;

                    // Restamos un año si la fecha de nacimiento ya pasó este año
                    if (FechaNacimiento.Value > hoy.AddYears(-edad))
                        edad--;

                    return edad;
                }
                return 0;
            }
        }
    }
}
